# Use root/example as user/password credentials
version: '3.1'

services:
  db:
    image: mysql:8
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - 3308:3306
    environment:
      MYSQL_DATABASE: css
      MYSQL_USER: dev
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password

  # adminer:
  #   image: adminer
  #   restart: always
  #   ports:
  #     - 8080:8080